In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
# Veri yükleme
veriler = pd.read_csv("../Docs/veriler.csv")
print(veriler)

   ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k


In [4]:
boy = veriler[["boy"]]
print(boy)

    boy
0   130
1   125
2   135
3   133
4   129
5   180
6   190
7   175
8   177
9   185
10  165
11  155
12  160
13  162
14  167
15  174
16  193
17  187
18  183
19  159
20  164
21  166


In [5]:
boykilo = veriler[["boy","kilo"]]
print(boykilo)

    boy  kilo
0   130    30
1   125    36
2   135    34
3   133    30
4   129    38
5   180    90
6   190    80
7   175    90
8   177    60
9   185   105
10  165    55
11  155    50
12  160    58
13  162    59
14  167    62
15  174    70
16  193    90
17  187    80
18  183    88
19  159    40
20  164    66
21  166    56


In [6]:
veriler

ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k

In [7]:
# Eksik veriler
eksik_veriler = pd.read_csv("../Docs/eksikveriler.csv")
eksik_veriler.isnull().sum().sum()

2

In [8]:
imputer = SimpleImputer(missing_values = np.nan, strategy = "mean")
yas = eksik_veriler.iloc[:,1:4].values

# Fit ile öğrenme
imputer.fit(yas[:,1:4])

# Transform ile uygulama
yas[:,1:4] = imputer.transform(yas[:,1:4])
print(yas)

[[130.    30.    10.  ]
 [125.    36.    11.  ]
 [135.    34.    10.  ]
 [133.    30.     9.  ]
 [129.    38.    12.  ]
 [180.    90.    30.  ]
 [190.    80.    25.  ]
 [175.    90.    35.  ]
 [177.    60.    22.  ]
 [185.   105.    33.  ]
 [165.    55.    27.  ]
 [155.    50.    44.  ]
 [160.    58.    28.45]
 [162.    59.    41.  ]
 [167.    62.    55.  ]
 [174.    70.    47.  ]
 [193.    90.    28.45]
 [187.    80.    27.  ]
 [183.    88.    28.  ]
 [159.    40.    29.  ]
 [164.    66.    32.  ]
 [166.    56.    42.  ]]


In [9]:
# Kategorik veriler
veriler = pd.read_csv("../Docs/veriler.csv")
ulke = veriler.iloc[:,0:1].values
print(ulke)

[['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['us']
 ['us']
 ['us']
 ['us']
 ['us']
 ['us']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']]


In [10]:
le = preprocessing.LabelEncoder()
ulke[:,0] = le.fit_transform(veriler.iloc[:,0])
print(ulke)

[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [11]:
# One Hot Encoding
ohe = preprocessing.OneHotEncoder()
ulke = ohe.fit_transform(ulke).toarray()
print(ulke)

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [12]:
# Verilerin birleştirilmesi ve DataFrame Oluşturulması
sonuc = pd.DataFrame(data = ulke, index = range(22), columns = ["fr","tr","us"])
sonuc

fr   tr   us
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0

In [13]:
sonuc2 = pd.DataFrame(data = yas, index = range(22), columns = ["boy","kilo","yas"])
sonuc2

boy   kilo    yas
0   130.0   30.0  10.00
1   125.0   36.0  11.00
2   135.0   34.0  10.00
3   133.0   30.0   9.00
4   129.0   38.0  12.00
5   180.0   90.0  30.00
6   190.0   80.0  25.00
7   175.0   90.0  35.00
8   177.0   60.0  22.00
9   185.0  105.0  33.00
10  165.0   55.0  27.00
11  155.0   50.0  44.00
12  160.0   58.0  28.45
13  162.0   59.0  41.00
14  167.0   62.0  55.00
15  174.0   70.0  47.00
16  193.0   90.0  28.45
17  187.0   80.0  27.00
18  183.0   88.0  28.00
19  159.0   40.0  29.00
20  164.0   66.0  32.00
21  166.0   56.0  42.00

In [14]:
cinsiyet = veriler.iloc[:,-1].values
cinsiyet

array(['e', 'e', 'k', 'k', 'e', 'e', 'e', 'e', 'k', 'e', 'k', 'k', 'k',
       'k', 'k', 'e', 'e', 'e', 'e', 'k', 'k', 'k'], dtype=object)

In [15]:
sonuc3 = pd.DataFrame(data = cinsiyet, index = range(22), columns = ["cinsiyet"])
sonuc3

cinsiyet
0         e
1         e
2         k
3         k
4         e
5         e
6         e
7         e
8         k
9         e
10        k
11        k
12        k
13        k
14        k
15        e
16        e
17        e
18        e
19        k
20        k
21        k

In [16]:
# Verileri birleştirme
s = pd.concat([sonuc,sonuc2], axis = 1)
s

fr   tr   us    boy   kilo    yas
0   0.0  1.0  0.0  130.0   30.0  10.00
1   0.0  1.0  0.0  125.0   36.0  11.00
2   0.0  1.0  0.0  135.0   34.0  10.00
3   0.0  1.0  0.0  133.0   30.0   9.00
4   0.0  1.0  0.0  129.0   38.0  12.00
5   0.0  1.0  0.0  180.0   90.0  30.00
6   0.0  1.0  0.0  190.0   80.0  25.00
7   0.0  1.0  0.0  175.0   90.0  35.00
8   0.0  1.0  0.0  177.0   60.0  22.00
9   0.0  0.0  1.0  185.0  105.0  33.00
10  0.0  0.0  1.0  165.0   55.0  27.00
11  0.0  0.0  1.0  155.0   50.0  44.00
12  0.0  0.0  1.0  160.0   58.0  28.45
13  0.0  0.0  1.0  162.0   59.0  41.00
14  0.0  0.0  1.0  167.0   62.0  55.00
15  1.0  0.0  0.0  174.0   70.0  47.00
16  1.0  0.0  0.0  193.0   90.0  28.45
17  1.0  0.0  0.0  187.0   80.0  27.00
18  1.0  0.0  0.0  183.0   88.0  28.00
19  1.0  0.0  0.0  159.0   40.0  29.00
20  1.0  0.0  0.0  164.0   66.0  32.00
21  1.0  0.0  0.0  166.0   56.0  42.00

In [17]:
# Veri Kümesinin Eğitim ve Test Olarak Bölünmesi
x_train, x_test, y_train, y_test = train_test_split(s,sonuc3,test_size = 0.33, random_state = 0)
?train_test_split

Signature:
train_test_split(
    *arrays,
    test_size=None,
    train_size=None,
    random_state=None,
    shuffle=True,
    stratify=None,
)
Docstring:
Split arrays or matrices into random train and test subsets.

Quick utility that wraps input validation and
``next(ShuffleSplit().split(X, y))`` and application to input data
into a single call for splitting (and optionally subsampling) data in a
oneliner.

Read more in the :ref:`User Guide <cross_validation>`.

Parameters
----------
*arrays : sequence of indexables with same length / shape[0]
    Allowed inputs are lists, numpy arrays, scipy-sparse
    matrices or pandas dataframes.

test_size : float or int, default=None
    If float, should be between 0.0 and 1.0 and represent the proportion
    of the dataset to include in the test split. If int, represents the
    absolute number of test samples. If None, the value is set to the
    complement of the train size. If ``train_size`` is also None, it will
    be set to 0.25.

train

In [18]:
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.fit_transform(x_test)